/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_inventory_application;
import java.util.*;
import InventApp.*;
import java.util.stream.Collectors;   
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.FileOutputStream;
/**
 *
 * @author master
 */
public class PREFACTURACION_FORM extends javax.swing.JFrame {

    Prefactura nuevaPrefactura;
    
    public PREFACTURACION_FORM() {
        initComponents();
        nuevaPrefactura = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooser_FECHAINICIAL = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser_FECHAFINAL = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jButton_CSVGUARDAR = new javax.swing.JButton();
        jButton_GENERAR = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_PREFACTURA = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("GENERACION DE PREFACTURA");

        jLabel2.setText("Fecha inicial");

        jLabel3.setText("Fecha final");

        jButton_CSVGUARDAR.setText("Guardar CSV");
        jButton_CSVGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CSVGUARDARActionPerformed(evt);
            }
        });

        jButton_GENERAR.setText("Generar");
        jButton_GENERAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GENERARActionPerformed(evt);
            }
        });

        jTable_PREFACTURA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_PREFACTURA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jButton_GENERAR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser_FECHAINICIAL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser_FECHAFINAL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_CSVGUARDAR)
                            .addComponent(jLabel1))
                        .addGap(0, 486, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser_FECHAINICIAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser_FECHAFINAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_GENERAR, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_CSVGUARDAR)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CSVGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CSVGUARDARActionPerformed
        if(nuevaPrefactura != null){
            JFileChooser fileChooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("*.csv", "csv");
            fileChooser.setFileFilter(filter);
            int fcReturnValue = fileChooser.showSaveDialog(jPanel1);
            if(fcReturnValue == JFileChooser.APPROVE_OPTION){
                File temp = fileChooser.getSelectedFile();
                File file = new File(temp.getPath() + ".csv");
                try{
                    FileWriter writer = new FileWriter(file);
                    List<Integer> intList = Arrays.asList(1, 2, 3);
                    String result = "producto, unidades vendidas, venta total, codigo sat\n";
                    for(Object o : nuevaPrefactura.listaProductosVendidos){
                        result = result + o.toString() + "\n";
                    }
                    writer.write(result);
                    writer.close();
                }
                catch(IOException e){
                    System.out.println("Error al escribir el archivo CSV");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Debes generar la prefactura antes de exportar a CSV", "No existe prefactura",  1);
        }
    }//GEN-LAST:event_jButton_CSVGUARDARActionPerformed

    private void jButton_GENERARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GENERARActionPerformed

        Date fechaInicialConsulta = jDateChooser_FECHAINICIAL.getDate();
        Date fechaFinalConsulta = jDateChooser_FECHAFINAL.getDate();
        
        if(fechaInicialConsulta == null || fechaFinalConsulta == null){
            JOptionPane.showMessageDialog(null,  "Seleccione un rango de fechas","No hay fechas de consulta", 1);
            return;
        }
        
        this.nuevaPrefactura = new Prefactura(fechaInicialConsulta, fechaFinalConsulta);
        nuevaPrefactura.obtenerVentasPeriodo();
        String[] colNames = {"Nombre del producto","Unidades vendidas","Venta total","Clave del SAT"};
        Object[][] rows = new Object[nuevaPrefactura.listaProductosVendidos.size()][4];
        
        DefaultTableModel model = (DefaultTableModel) jTable_PREFACTURA.getModel();
        
        for(int i = 0; i < nuevaPrefactura.listaProductosVendidos.size(); i++){
            rows[i][0] = nuevaPrefactura.listaProductosVendidos.get(i).getNombreProducto();
            rows[i][1] = nuevaPrefactura.listaProductosVendidos.get(i).getVolumen();
            rows[i][2] = nuevaPrefactura.listaProductosVendidos.get(i).getColocacion();
            rows[i][3] = nuevaPrefactura.listaProductosVendidos.get(i).getSatCodigo();
        }
        
        model.setDataVector(rows, colNames);


        jTable_PREFACTURA.setModel(model);
        jTable_PREFACTURA.setRowHeight(20);
        jTable_PREFACTURA.setEnabled(false);
    }//GEN-LAST:event_jButton_GENERARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PREFACTURACION_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PREFACTURACION_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PREFACTURACION_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PREFACTURACION_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PREFACTURACION_FORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CSVGUARDAR;
    private javax.swing.JButton jButton_GENERAR;
    private com.toedter.calendar.JDateChooser jDateChooser_FECHAFINAL;
    private com.toedter.calendar.JDateChooser jDateChooser_FECHAINICIAL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_PREFACTURA;
    // End of variables declaration//GEN-END:variables
}
