package InventApp.ViewControllers;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jerry
 */
public class HomeFormViewController extends javax.swing.JFrame {

    /**
     * Creates new form Home_Form
     */
    
    public HomeFormViewController() {
        initComponents();

        ImageIcon imgThisImg = new ImageIcon("src\\images\\my_store.png");
        reloadContainerComponents();
        jLabel_MONEYNOW.setFont(jLabel_MONEYNOW.getFont().deriveFont (48.0f));
        jLabel_FULLNAME.setFont(jLabel_FULLNAME.getFont().deriveFont (32.0f));
    }
    
    private void reloadContainerComponents(){
        String moneyString = "$"+String.valueOf(InventApp.Configuracion.config.getSesionActual().getCashInSession());
        String cashierName = InventApp.Configuracion.config.getSesionActual().getCajeroEnSesion().getNombreCajero();
        System.out.println(cashierName);
        jLabel_FULLNAME.setText("Bienvenido, " + cashierName);
        Date currentDate = new Date();
        jLabel_DATETIME.setText("Hoy es "+currentDate.toString());
        jLabel_MONEYNOW.setText(moneyString); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_BackgroundImage = new javax.swing.JLabel();
        jLabel_FULLNAME = new javax.swing.JLabel();
        jLabel_MONEYNOW = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_TODAYSALES = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel_DATETIME = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_PRODUCT_ = new javax.swing.JMenu();
        jMenu_CATEGORY_ = new javax.swing.JMenu();
        jMenu_CUSTOMER_ = new javax.swing.JMenu();
        jMenu_ORDER_ = new javax.swing.JMenu();
        jMenu5_USER_ = new javax.swing.JMenu();
        jMenu_FACT = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_FULLNAME.setText("Bienvenido, ");

        jLabel_MONEYNOW.setText("jLabel2");

        jLabel3.setText("Dinero en caja");

        jLabel4.setText("Ventas del dia");

        jTable_TODAYSALES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_TODAYSALES);

        jButton1.setText("CORTE DE CAJA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel_DATETIME.setText("jLabel1");

        jMenu_PRODUCT_.setBackground(new java.awt.Color(249, 105, 14));
        jMenu_PRODUCT_.setText("  INVENTARIO  |");
        jMenu_PRODUCT_.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu_PRODUCT_.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jMenu_PRODUCT_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_PRODUCT_MouseClicked(evt);
            }
        });
        jMenu_PRODUCT_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_PRODUCT_ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_PRODUCT_);

        jMenu_CATEGORY_.setBackground(new java.awt.Color(249, 105, 14));
        jMenu_CATEGORY_.setText("  CATEGORIAS  |");
        jMenu_CATEGORY_.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu_CATEGORY_.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jMenu_CATEGORY_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_CATEGORY_MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_CATEGORY_);

        jMenu_CUSTOMER_.setBackground(new java.awt.Color(249, 105, 14));
        jMenu_CUSTOMER_.setText("  MIS CLIENTES  |");
        jMenu_CUSTOMER_.setToolTipText("");
        jMenu_CUSTOMER_.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu_CUSTOMER_.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jMenu_CUSTOMER_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_CUSTOMER_MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_CUSTOMER_);

        jMenu_ORDER_.setBackground(new java.awt.Color(249, 105, 14));
        jMenu_ORDER_.setText("  PUNTO DE VENTA  |");
        jMenu_ORDER_.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu_ORDER_.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jMenu_ORDER_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_ORDER_MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_ORDER_);

        jMenu5_USER_.setBackground(new java.awt.Color(249, 105, 14));
        jMenu5_USER_.setText("USUARIOS |");
        jMenu5_USER_.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu5_USER_.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jMenu5_USER_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5_USER_MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5_USER_);

        jMenu_FACT.setBackground(new java.awt.Color(249, 105, 14));
        jMenu_FACT.setText("PREFACTURAS | ");
        jMenu_FACT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu_FACT.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jMenu_FACT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_FACTMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_FACT);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_MONEYNOW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_DATETIME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel_FULLNAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_BackgroundImage, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_BackgroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel_FULLNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_DATETIME)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_MONEYNOW, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_PRODUCT_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_PRODUCT_ActionPerformed
        
    }//GEN-LAST:event_jMenu_PRODUCT_ActionPerformed

    // open the product form
    private void jMenu_PRODUCT_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_PRODUCT_MouseClicked
        
                InventoryViewController productForm = new InventoryViewController();
                productForm.pack();
                productForm.setVisible(true);
                productForm.setLocationRelativeTo(null);
                productForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenu_PRODUCT_MouseClicked

    // open the category form
    private void jMenu_CATEGORY_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_CATEGORY_MouseClicked
        
        CategoriesFormViewController categoryForm = new CategoriesFormViewController();
                categoryForm.pack();
                categoryForm.setVisible(true);
                categoryForm.setLocationRelativeTo(null);
                categoryForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenu_CATEGORY_MouseClicked

    // open the customer form
    private void jMenu_CUSTOMER_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_CUSTOMER_MouseClicked
        
        CustomerFormViewController customerForm = new CustomerFormViewController();
                customerForm.pack();
                customerForm.setVisible(true);
                customerForm.setLocationRelativeTo(null);
                customerForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenu_CUSTOMER_MouseClicked

    // open the order form
    private void jMenu_ORDER_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_ORDER_MouseClicked
        
        POSViewController orderForm = new POSViewController();
                orderForm.pack();
                orderForm.setVisible(true);
                orderForm.setLocationRelativeTo(null);
                orderForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenu_ORDER_MouseClicked

    // open the user form
    private void jMenu5_USER_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5_USER_MouseClicked
        
        UserManagementViewController userForm = new UserManagementViewController();
                userForm.pack();
                userForm.setVisible(true);
                userForm.setLocationRelativeTo(null);
                userForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenu5_USER_MouseClicked

    private void jMenu_FACTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_FACTMouseClicked
        PrefacturacionViewController moduloPrefac = new PrefacturacionViewController();
                moduloPrefac.pack();
                moduloPrefac.setVisible(true);
                moduloPrefac.setLocationRelativeTo(null);
                moduloPrefac.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenu_FACTMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFormViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFormViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFormViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFormViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFormViewController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_BackgroundImage;
    private javax.swing.JLabel jLabel_DATETIME;
    private javax.swing.JLabel jLabel_FULLNAME;
    private javax.swing.JLabel jLabel_MONEYNOW;
    public javax.swing.JMenu jMenu5_USER_;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_CATEGORY_;
    private javax.swing.JMenu jMenu_CUSTOMER_;
    public javax.swing.JMenu jMenu_FACT;
    private javax.swing.JMenu jMenu_ORDER_;
    private javax.swing.JMenu jMenu_PRODUCT_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_TODAYSALES;
    // End of variables declaration//GEN-END:variables
}
